CREATE TABLE Genre
(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(250),
  themoviedb_id INT,
  PRIMARY KEY (id)
)

CREATE TABLE MOVIE
(
  id INT NOT NULL AUTO_INCREMENT,
  original_title VARCHAR(100),
  PRIMARY KEY (id)
)
